name: PyTest
on:
  push:
  schedule:
    - cron: '0 0 1,7,14,21,28 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel
          python -m pip install -r requirements.txt
          python -m pip install pytest pytest-asyncio

      - name: Run test suite
        run: |
          pytest test.py